import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import worker from '../worker.js';
const sql=new DatabaseSync(':memory:');sql.exec(fs.readFileSync('drizzle/0000_acoustic_spencer_smythe.sql','utf8'));
function prepare(q,v=[]){return {bind(...x){return prepare(q,x);},async first(){return sql.prepare(q).get(...v)||null;},async all(){return {results:sql.prepare(q).all(...v)};},async run(){return sql.prepare(q).run(...v);}};}
const env={DB:{prepare,async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}},ASSETS:{fetch:async()=>new Response('asset')},BUCKET:{put:async()=>{},delete:async()=>{}}};
test('portable worker serves every public route and blocks removed routes',async()=>{for(const route of ['/','/about','/quote','/shop','/shop?category=processors','/product/rtx-4070-super','/cart','/wishlist','/checkout']){const r=await worker.fetch(new Request('https://store.test'+route),env);assert.equal(r.status,200,route);const html=await r.text();assert.match(html,/<title>/);assert.match(html,/Digitron/);assert.doesNotMatch(html,/@foreach|<\?php|Starter Project|data-login-url|customer\.login/);assert.equal(r.headers.get('X-Frame-Options'),'DENY');}for(const route of ['/admin','/account','/login','/product/nonexistent'])assert.equal((await worker.fetch(new Request('https://store.test'+route),env)).status,404);});
test('portable API establishes a secure cookie and enforces same-origin writes',async()=>{const first=await worker.fetch(new Request('https://store.test/api/state'),env);assert.equal(first.status,200);const cookie=first.headers.get('Set-Cookie').split(';')[0];const add=await worker.fetch(new Request('https://store.test/api/cart',{method:'POST',headers:{Origin:'https://store.test',Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({action:'add',id:1,quantity:1})}),env);assert.equal(add.status,200);assert.equal((await add.json()).items.length,1);const bad=await worker.fetch(new Request('https://store.test/api/cart',{method:'POST',headers:{Origin:'https://elsewhere.test',Cookie:cookie,'Content-Type':'application/json'},body:'{}'}),env);assert.equal(bad.status,403);});
test('portable worker routes assets without database calls',async()=>{const r=await worker.fetch(new Request('https://store.test/videos/slide-hero.mp4'),{ASSETS:env.ASSETS});assert.equal(await r.text(),'asset');});
